name: Test Action

on: 
  push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate sdRDM library
        uses: ./
        with:
          library_name: "user"
          # schema_path: "./.github/workflows/model.md"
          push: "true"
